name: dank-formal unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Z3
      run: |
        sudo apt-get install -y z3
        z3 --version

    - name: Install Verilator
      run: |
        sudo apt-get install -y verilator
        verilator --version

    - name: Cache Yosys
      id: cache-yosys
      uses: actions/cache@v2
      with:
        path: yosys
        key: ${{ runner.os }}-yosys-b00e55a

    - name: Compile Yosys
      if: steps.cache-yosys.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/YosysHQ/yosys.git yosys
        cd yosys
        git checkout b00e55a
        sudo apt-get install -y build-essential clang bison flex \
            libreadline-dev gawk tcl-dev libffi-dev git \
            graphviz xdot pkg-config python3 libboost-system-dev \
            libboost-python-dev libboost-filesystem-dev zlib1g-dev
        make config-gcc
        make -j2

    - name: Install Yosys
      run: |
        cd yosys
        sudo make install
        yosys -version

    - name: Install SymbiYosys
      run: |
        git clone https://github.com/YosysHQ/SymbiYosys.git SymbiYosys
        cd SymbiYosys
        sudo make install

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile
      run: sbt compile

    - name: Unit Tests
      run: sbt test
