name: dank-formal unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Z3
      run: |
        sudo apt-get install -y z3
        z3 --version

    - name: Install Verilator
      run: |
        sudo apt-get install -y verilator
        verilator --version

    - name: Cache Yosys
      id: cache-yosys
      uses: actions/cache@v2
      with:
        path: |
          yosys/**/Makefile
          yosys/**/Makefile.inc
          yosys/yosys
          yosys/yosys-abc
          yosys/yosys-filterlib
          yosys/yosys-smtbmc
          yosys/share/
        key: ${{ runner.os }}-yosys-b000491-2

    - name: Compile Yosys
      if: steps.cache-yosys.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/YosysHQ/yosys.git yosys
        cd yosys
        git checkout b000491
        sudo apt-get install -y build-essential clang bison flex \
            libreadline-dev gawk tcl-dev libffi-dev git \
            graphviz xdot pkg-config python3 libboost-system-dev \
            libboost-python-dev libboost-filesystem-dev zlib1g-dev
        make config-gcc
        make -j2
        sudo make install
        yosys -version

    - name: Install Yosys
      run: |
        cd yosys
        sudo make install
        yosys -version

    - name: Compile and Install Yices2
      run: |
        sudo apt install -y gperf
        wget https://github.com/SRI-CSL/yices2/archive/Yices-2.6.2.zip
        unzip Yices-2.6.2.zip
        cd yices2-Yices-2.6.2/
        autoconf
        ./configure
        make -j2
        sudo make install
        yices-smt2 --version

    - name: Install SymbiYosys
      run: |
        git clone https://github.com/YosysHQ/SymbiYosys.git SymbiYosys
        cd SymbiYosys
        sudo make install

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile
      run: sbt compile

    - name: Unit Tests
      run: sbt test
